In [4]:
import numpy as np

In [8]:
a = np.array([1,2,3])
print(a)
print(type(a))
print(a[0], a[1], a[2])

[1 2 3]
<class 'numpy.ndarray'>
1 2 3


In [9]:
a[0] = 5
print(a)

[5 2 3]


In [11]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
print(b[0, 0], b[0, 1], b[1, 0])

1 2 4


In [14]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(c[0, 0], c[1, 1], c[2, 2])

1 5 9


In [30]:
# Array filled with zeros

a = np.zeros((2,2))
print(a)

print("-----------------------")

# Array filled with ones

b = np.ones((3,3))
print(b)

print("-----------------------")

# Create an empty array with random content

c = np.empty((2,3))
print(c)

print("-----------------------")

# Create a constant array

d = np.full((2,2), 7)
print(d)

print("-----------------------")

## Create a 2x2 identity matrix

e = np.eye(2)
print(e)

print("-----------------------")

# Create an array with a range of elements

f = np.arange(4)
print(f)

print("-----------------------")

g = np.arange(1,10,3)
print(g)

print("-----------------------")

# Create an array with random values
h = np.random.random((2,2))
print(h)

[[0. 0.]
 [0. 0.]]
-----------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----------------------
[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]
-----------------------
[[7 7]
 [7 7]]
-----------------------
[[1. 0.]
 [0. 1.]]
-----------------------
[0 1 2 3]
-----------------------
[1 4 7]
-----------------------
[[0.41396555 0.9362057 ]
 [0.81688904 0.37974582]]


### **Explore the differences between np.random.random(), np.random rand() and np.random.randn().**

| Function | Distribution | Range | Input Syntax (Shape) |
| :--- | :--- | :--- | :--- |
| **`np.random.random()`** | Uniform | $[0.0, 1.0)$ | Tuple/List: `(2, 3)` |
| **`np.random.rand()`** | Uniform | $[0.0, 1.0)$ | Separate Arguments: `2, 3` |
| **`np.random.randn()`** | Standard Normal (Gaussian) | $(-\infty, +\infty)$ | Separate Arguments: `2, 3` |



In [31]:
x = np.random.random((2, 3))
print(x)

[[0.66899379 0.74520975 0.67148036]
 [0.88513331 0.04657021 0.87179428]]


In [32]:
y = np.random.rand(2, 3)
print(y)

[[0.99197173 0.16460869 0.18028602]
 [0.8017603  0.45278967 0.27267466]]


In [33]:
z = np.random.randn(2, 3)
print(z)

[[-0.61451394  0.19941078 -0.71205428]
 [-1.54543754 -0.04264048 -0.03951709]]


## NumPy Array Attributes

Key attributes to inspect the structure and memory layout of an array:

* **`.ndim`**: The number of axes (dimensions) in the array.
* **`.shape`**: A tuple indicating the size of the array in each dimension (e.g., rows, columns).
* **`.size`**: The total number of elements in the array (product of the shape).
* **`.dtype`**: The data type of the elements (e.g., `int64`, `float32`).

| Attribute | Description | Return Type | Example Output |
| :--- | :--- | :--- | :--- |
| **`.ndim`** | Number of dimensions | Integer | `2` |
| **`.shape`** | Dimensions (rows, cols) | Tuple | `(3, 4)` |
| **`.size`** | Total element count | Integer | `12` |
| **`.dtype`** | Data type of elements | Object | `float64` |

In [36]:
# Creating a 3-Dimensional array (2 layers, 3 rows, 4 columns)

arr = np.random.randint(10, size=(2, 3, 4))
print(arr)

[[[2 7 1 9]
  [9 5 8 3]
  [8 0 0 3]]

 [[4 8 8 5]
  [5 1 1 4]
  [9 5 6 0]]]
